name: *nkase

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: html

    steps:
    - name: nkased
      uses: actions/revert
      with:
        master-version: @nkased
    - name: Nora Kased
      run: |
       
       
